// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQNYPieXFDpULPar2ydLwxm-ICzLApea4',
    appId: '1:479513638007:web:9fa61325a9cd8eb3dc4272',
    messagingSenderId: '479513638007',
    projectId: 'auth-login-a5f83',
    authDomain: 'auth-login-a5f83.firebaseapp.com',
    storageBucket: 'auth-login-a5f83.appspot.com',
    measurementId: 'G-VGT170PFHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeURxg1KfWrZvYQ6NKIQywZGHxSaz_LnA',
    appId: '1:479513638007:android:f21f6332792b9a59dc4272',
    messagingSenderId: '479513638007',
    projectId: 'auth-login-a5f83',
    storageBucket: 'auth-login-a5f83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBV7-O0cuG793tP8gEiOZjLya1BCRJNgg',
    appId: '1:479513638007:ios:485f87e14519d43fdc4272',
    messagingSenderId: '479513638007',
    projectId: 'auth-login-a5f83',
    storageBucket: 'auth-login-a5f83.appspot.com',
    iosBundleId: 'com.example.authApplicationNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBV7-O0cuG793tP8gEiOZjLya1BCRJNgg',
    appId: '1:479513638007:ios:485f87e14519d43fdc4272',
    messagingSenderId: '479513638007',
    projectId: 'auth-login-a5f83',
    storageBucket: 'auth-login-a5f83.appspot.com',
    iosBundleId: 'com.example.authApplicationNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQNYPieXFDpULPar2ydLwxm-ICzLApea4',
    appId: '1:479513638007:web:851edc1ab41e0da9dc4272',
    messagingSenderId: '479513638007',
    projectId: 'auth-login-a5f83',
    authDomain: 'auth-login-a5f83.firebaseapp.com',
    storageBucket: 'auth-login-a5f83.appspot.com',
    measurementId: 'G-6RF923JM11',
  );
}
